# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - testweb5959

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Changed from windows-latest for better Node.js compatibility
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Verify repository files
        run: ls -la  # Helps debug file structure issues

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Changed from 22.x to match your app

      - name: Install dependencies
        run: npm install
        working-directory: ./  # Explicitly sets root directory

      - name: Build application
        run: npm run build --if-present
        working-directory: ./

      - name: Run tests
        run: npm run test --if-present
        working-directory: ./
      
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C36BCE134B0D40B68474BE736C96D9BF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8BAFD76A75DB4716A7F8A7658D6EF40F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1F0BF8EFFCBD4EEA8A3A3A89F29CED55 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'testweb5959'
          slot-name: 'Production'
          package: ./
